application: gcp-memo
module: default
version: 1
runtime: python27
api_version: 1
threadsafe: true
instance_class: F1

libraries:
- name: jinja2
  version: "2.6"
- name: webapp2
  version: "2.5.2"
- name: markupsafe
  version: latest

inbound_services:
- warmup

builtins:
- deferred: on

handlers:
- url: /(css|images|js|etc)/(.*)
  static_files: static_files/front/\1/\2
  upload: static_files/front/(css|images|js|etc)/(.*)
  secure: optional

- url: /_ah/(warmup|xrds|login_required)
  script: controllers.front.system.application
  secure: always

- url: /_ah/queue/deferred
  script: google.appengine.ext.deferred.deferred.application
  login: admin

- url: /member/(.*)
  script: controllers.front.member.application
  secure: always
  login: required

- url: (/)
  script: controllers.front.index.application
  secure: optional

- url: /(.*)/(.*)
  script: controllers.front.\1.application
  secure: optional

